fieldLayouts:
  20e7215a-39c8-421f-835a-f14244493bd7:
    tabs:
      -
        fields:
          41fdb4c8-4774-4101-918f-1412190b085b:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
handle: devmodeUsers
hasUrls: true
name: 'Devmode Users'
settings:
  autoFocalPoint: ''
  bucket: $S3_BUCKET
  bucketSelectionMode: manual
  cfDistributionId: $CLOUDFRONT_DISTRIBUTION_ID
  cfPrefix: $CLOUDFRONT_PATH_PREFIX
  expires: '3 months'
  keyId: $S3_KEY_ID
  makeUploadsPublic: ''
  region: $S3_REGION
  secret: $S3_SECRET
  storageClass: ''
  subfolder: users
sortOrder: 6
type: craft\awss3\Volume
url: $CLOUDFRONT_URL
