fieldLayouts:
  a3429f83-028c-4ceb-954f-7cfe44643b98:
    tabs:
      -
        fields:
          1be1c156-82fa-4f08-bb63-6d3417da2844:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
handle: devmodeSite
hasUrls: true
name: 'Devmode Site'
settings:
  autoFocalPoint: ''
  bucket: $S3_BUCKET
  bucketSelectionMode: manual
  cfDistributionId: CLOUDFRONT_DISTRIBUTION_ID
  cfPrefix: $CLOUDFRONT_PATH_PREFIX
  expires: '3 months'
  keyId: $S3_KEY_ID
  makeUploadsPublic: ''
  region: $S3_REGION
  secret: $S3_SECRET
  storageClass: ''
  subfolder: site
sortOrder: 5
type: craft\awss3\Volume
url: $CLOUDFRONT_URL
