fieldLayouts:
  20e7215a-39c8-421f-835a-f14244493bd7:
    tabs:
      -
        fields:
          41fdb4c8-4774-4101-918f-1412190b085b: # Profile Optimized Images
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fs: devmodeUsers
handle: devmodeUsers
hasUrls: true
name: 'Devmode Users'
sortOrder: 6
url: $CLOUDFRONT_URL
