fieldLayouts:
  a3429f83-028c-4ceb-954f-7cfe44643b98:
    tabs:
      -
        fields:
          1be1c156-82fa-4f08-bb63-6d3417da2844: # Optimized Images
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fs: devmodeSite
handle: devmodeSite
hasUrls: true
name: 'Devmode Site'
sortOrder: 5
url: $CLOUDFRONT_URL
