tabs:
  -
    fields:
      31b8c511-37f9-4d83-956d-5aa215572122:
        required: false
        sortOrder: 4
      380e3b7e-07de-4d39-b0e5-360f5e87d00d:
        required: false
        sortOrder: 2
      406c20cb-9b86-4b0d-9123-1ce57220e2a8:
        required: false
        sortOrder: 5
      9687721c-33b8-4a40-abb7-5c42e07ce274:
        required: false
        sortOrder: 3
      c05161c0-a294-4d47-8909-1cfc88c2f970:
        required: false
        sortOrder: 1
      d6df6fe7-14f3-42a3-9949-dcee7c8c26d9:
        required: false
        sortOrder: 6
    name: Profile
    sortOrder: 1
