enableVersioning: false
handle: episodesIndex
name: 'Episodes Index'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  2a4761bd-2461-4db9-96a0-4f52b8cef633: # devMode
    enabledByDefault: true
    hasUrls: true
    template: episodes/index
    uriFormat: episodes
type: single
