contentColumnType: string
fieldGroup: 0c790066-43c5-4b67-b6d9-8492fa40cf71
handle: showEmail
instructions: ''
name: 'Show Email'
searchable: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
