contentColumnType: integer(10)
fieldGroup: bfbd2913-36d8-4e54-9f9c-644e793f0ae9
handle: episodeNumber
instructions: ''
name: 'Episode Number'
searchable: true
settings:
  decimals: '0'
  max: null
  min: '1'
  size: '10'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
