contentColumnType: string
fieldGroup: bfbd2913-36d8-4e54-9f9c-644e793f0ae9 # Episodes
handle: episodeGuests
instructions: ''
name: 'Episode Guests'
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  source: null
  sources:
    - 'section:214e4dc6-a454-4df0-a1f5-cd94ecdab53f' # Guests
  targetSiteId: null
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
