contentColumnType: string(255)
fieldGroup: 12aa936c-807f-4ec3-81dc-69283a344171 # Profile
handle: profileGithubUrl
instructions: ''
name: 'Profile GitHub URL'
searchable: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
