columnSuffix: null
contentColumnType: string
fieldGroup: bfbd2913-36d8-4e54-9f9c-644e793f0ae9 # Episodes
handle: relatedEpisodes
instructions: ''
name: 'Related Episodes'
searchable: false
settings:
  allowSelfRelations: false
  limit: '3'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources:
    - 'section:c1f6af30-7375-4feb-92ef-a3ed16ba69b2' # Episodes
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
