contentColumnType: string(255)
fieldGroup: 0c790066-43c5-4b67-b6d9-8492fa40cf71
handle: showRssFeedUrl
instructions: ''
name: 'Show RSS Feed URL'
searchable: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
