contentColumnType: text
fieldGroup: 0c790066-43c5-4b67-b6d9-8492fa40cf71 # Show
handle: showTitle
instructions: ''
name: 'Show Title'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
