fieldLayouts:
  92845533-f123-4a66-937a-1f9ed6ddea24:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 324e7a11-3346-41e7-a29d-4636ab907e51 # Episode Number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8011817c-9518-4a31-9aa8-cad6d4a08b81 # Episode Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 61953a92-8b34-4678-9bae-fd5a45142f26 # Episode Tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a5cf9c0d-1797-4a60-8c47-bc28c5f01a95 # Episode Hosts
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7e338b73-ac10-44cf-892e-04afc0164991 # Episode Guests
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0090f7a3-1e22-4fb5-9ae0-01de38805601 # Episode Media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 07f04bdf-277d-4010-9fbe-497cd9593324 # Related Episodes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8c9dd611-b43b-4e22-b076-3f6a6362c93e # Episode Reference Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Episodes
        sortOrder: 1
handle: episodes
hasTitleField: true
name: Episodes
section: c1f6af30-7375-4feb-92ef-a3ed16ba69b2
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
