fieldLayouts:
  93ce2e82-1407-4642-9ca7-b1fea1df0a56:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\entries\EntryTitleField
          -
            fieldUid: c05161c0-a294-4d47-8909-1cfc88c2f970 # Profile Company
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 380e3b7e-07de-4d39-b0e5-360f5e87d00d # Profile Title
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 9687721c-33b8-4a40-abb7-5c42e07ce274 # Profile Bio
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 31b8c511-37f9-4d83-956d-5aa215572122 # Profile URL
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d6df6fe7-14f3-42a3-9949-dcee7c8c26d9 # Profile GitHub URL
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 406c20cb-9b86-4b0d-9123-1ce57220e2a8 # Profile Twitter URL
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Profile
        sortOrder: 1
handle: guests
hasTitleField: true
name: Guests
section: 214e4dc6-a454-4df0-a1f5-cd94ecdab53f
sortOrder: 1
titleFormat: null
