fieldLayouts:
  293a1b30-3925-4331-8e4e-90693d3a8ce5:
    tabs:
      -
        elements:
          -
            instructions: null
            label: null
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 18d7721b-780b-4a44-976a-716c3df0bb7a # Error Headline
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e1087165-5769-428d-bf14-c98e6011cf5e # Error Text
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 4d90d0e7-b705-4035-b396-2f82ce5bb871 # Error Image
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Errors
        sortOrder: 1
handle: notFound
hasTitleField: false
name: '404 Not Found'
section: 52b673e7-3d80-44a4-94f7-43eaafcc9d6f
sortOrder: 1
titleFormat: '{section.name|raw}'
