fieldLayouts:
  bf0b0ad9-5882-4afc-9e4d-5b687c94d4ad:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\entries\EntryTitleField
          -
            fieldUid: 18d7721b-780b-4a44-976a-716c3df0bb7a # Error Headline
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e1087165-5769-428d-bf14-c98e6011cf5e # Error Text
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 4d90d0e7-b705-4035-b396-2f82ce5bb871 # Error Image
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Errors
        sortOrder: 1
handle: serviceUnavailable
hasTitleField: true
name: '503 Service Unavailable'
section: 9089688f-6602-4d69-91cd-ec9a94c4bc6f # 503 Service Unavailable
sortOrder: 1
titleFormat: null
