fieldLayouts:
  87e65db2-3d89-4271-a91e-f06dc48b7a01:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 18d7721b-780b-4a44-976a-716c3df0bb7a
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e1087165-5769-428d-bf14-c98e6011cf5e
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 4d90d0e7-b705-4035-b396-2f82ce5bb871
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Errors
        sortOrder: 1
handle: siteOffline
hasTitleField: true
name: 'Site Offline'
section: 5f70b9e0-f42b-4fdb-bcf6-5e82691d89de
sortOrder: 1
titleFormat: null
