dateModified: 1623786955
email:
  fromEmail: andrew@nystudio107.com
  fromName: devMode
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0c790066-43c5-4b67-b6d9-8492fa40cf71: Show # Show
    1be1c156-82fa-4f08-bb63-6d3417da2844: 'Optimized Images' # Optimized Images
    2a4761bd-2461-4db9-96a0-4f52b8cef633: devMode # devMode
    4d90d0e7-b705-4035-b396-2f82ce5bb871: 'Error Image' # Error Image
    6def66f0-2a8f-4b88-9435-7f9cc1ccfe9c: 'Show Genre' # Show Genre
    7e338b73-ac10-44cf-892e-04afc0164991: 'Episode Guests' # Episode Guests
    07f04bdf-277d-4010-9fbe-497cd9593324: 'Related Episodes' # Related Episodes
    8c9dd611-b43b-4e22-b076-3f6a6362c93e: 'Episode Reference Links' # Episode Reference Links
    12aa936c-807f-4ec3-81dc-69283a344171: Profile # Profile
    18d7721b-780b-4a44-976a-716c3df0bb7a: 'Error Headline' # Error Headline
    19e4e8ba-93c2-4a86-8c57-9b54d46e0981: Site # Site
    31b8c511-37f9-4d83-956d-5aa215572122: 'Profile URL' # Profile URL
    41fdb4c8-4774-4101-918f-1412190b085b: 'Profile Optimized Images' # Profile Optimized Images
    087ee23d-4f8f-42d4-af12-99fcc2462247: 'Show Info' # Show Info
    88db3e41-57f4-404d-b3ea-762b09c37afe: Errors # Errors
    0090f7a3-1e22-4fb5-9ae0-01de38805601: 'Episode Media' # Episode Media
    324e7a11-3346-41e7-a29d-4636ab907e51: 'Episode Number' # Episode Number
    380e3b7e-07de-4d39-b0e5-360f5e87d00d: 'Profile Title' # Profile Title
    406c20cb-9b86-4b0d-9123-1ce57220e2a8: 'Profile Twitter URL' # Profile Twitter URL
    428ec106-b2d1-4d48-a5fa-de192155dff5: 'Show URL' # Show URL
    913ea665-c268-4177-8054-fe76f80101c6: Episodes # Episodes
    2405ed1c-fd52-4264-a96a-f6e6fab437b5: 'Show Sub-Title' # Show Sub-Title
    34348a98-83b9-4f2d-8e14-0437ec964a15: devMode # devMode
    49649e9a-033b-4ddf-9f3d-26a480502993: About # About
    61953a92-8b34-4678-9bae-fd5a45142f26: 'Episode Tags' # Episode Tags
    8011817c-9518-4a31-9aa8-cad6d4a08b81: 'Episode Summary' # Episode Summary
    9687721c-33b8-4a40-abb7-5c42e07ce274: 'Profile Bio' # Profile Bio
    14605669-4768-4f57-88d6-1f06480a9b80: 'Show iTunes URL' # Show iTunes URL
    86909527-3ec4-4d57-a44c-167649eb86bf: 'Show Description' # Show Description
    a5cf9c0d-1797-4a60-8c47-bc28c5f01a95: 'Episode Hosts' # Episode Hosts
    a8f2ec1a-a218-451c-a658-e3c600ddb5fa: 'Show Title' # Show Title
    ab0ca0e9-1308-472f-92a5-2ab0cbd84943: 'Show RSS Feed URL' # Show RSS Feed URL
    b5eb01ec-a6ed-4a08-9438-64e7138b08f0: FAQs # FAQs
    bda219fa-bace-4d8b-ad3a-08243caaf6ca: 'Show Image' # Show Image
    bfbd2913-36d8-4e54-9f9c-644e793f0ae9: Episodes # Episodes
    c05161c0-a294-4d47-8909-1cfc88c2f970: 'Profile Company' # Profile Company
    ca279869-925f-4960-865c-96cacd2aa942: 'Show Email' # Show Email
    d6df6fe7-14f3-42a3-9949-dcee7c8c26d9: 'Profile GitHub URL' # Profile GitHub URL
    e1087165-5769-428d-bf14-c98e6011cf5e: 'Error Text' # Error Text
    eecc24bf-e253-43b8-b327-632e0dc07fa6: 'Show Technologies Links' # Show Technologies Links
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
  disqus:
    enabled: true
    licenseKey: null
    schemaVersion: 1.0.0
    settings:
      customLogin: false
      disqusPublicKey: $DISQUS_PUBLIC_KEY
      disqusSecretKey: $DISQUS_SECRET_KEY
      disqusShortname: devmode-fm
      loginButton: ''
      loginHeight: 400
      loginIcon: ''
      loginLogoutUrl: ''
      loginName: ''
      loginUrl: ''
      loginWidth: 800
      useSSO: false
  fastcgi-cache-bust:
    enabled: true
    licenseKey: null
    schemaVersion: 1.0.0
    settings:
      cachePath: /var/run/nginx-cache/devmode
  icalendar:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-optimize:
    enabled: true
    licenseKey: $PLUGIN_IMAGEOPTIMIZE_LICENSE
    schemaVersion: 1.0.0
    settings:
      allowUpScaledImageVariants: false
      assetVolumeSubFolders: true
      autoSharpenScaledImages: true
      createColorPalette: true
      createPlaceholderSilhouettes: true
      imageTransformTypeSettings:
        __assoc__:
          -
            - nystudio107\imageoptimizeimgix\imagetransforms\ImgixImageTransform
            -
              __assoc__:
                -
                  - domain
                  - ''
                -
                  - apiKey
                  - ''
                -
                  - securityToken
                  - ''
          -
            - nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - $SERVERLESS_SHARP_CLOUDFRONT_URL
          -
            - nystudio107\imageoptimizethumbor\imagetransforms\ThumborImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
                -
                  - securityKey
                  - ''
                -
                  - includeBucketPrefix
                  - ''
      lowerQualityRetinaImageVariants: false
      transformClass: nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
  minify:
    enabled: true
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  retour:
    enabled: true
    licenseKey: $PLUGIN_RETOUR_LICENSE
    schemaVersion: 3.0.10
    settings: null
  seomatic:
    enabled: true
    licenseKey: $PLUGIN_SEOMATIC_LICENSE
    schemaVersion: 3.0.10
    settings:
      addHrefLang: true
      addXDefaultHrefLang: true
      cpTitlePrefix: '⚙ '
      devModeCpTitlePrefix: '🚧⚙ '
      devModeTitlePrefix: '[devMode] '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      environment: live
      generatorEnabled: true
      headersEnabled: true
      maxDescriptionLength: 300
      maxTitleLength: 120
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: //
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      sitemapsEnabled: true
  transcoder:
    enabled: true
    licenseKey: $PLUGIN_TRANSCODER_LICENSE
    schemaVersion: 1.0.0
    settings: null
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typogrify:
    enabled: true
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  webperf:
    enabled: true
    licenseKey: $PLUGIN_WEBPERF_LICENSE
    schemaVersion: 1.0.1
    settings:
      automaticallyTrimDataSamples: true
      automaticallyTrimErrorSamples: true
      connectThreshold: 0.5
      craftDbMsThreshold: 2
      craftOtherMsThreshold: 2
      craftTotalMsThreshold: 2
      craftTwigMsThreshold: 2
      dashboardAverageColor: '#ffff00'
      dashboardFastColor: '#00c800'
      dashboardSlowColor: '#c80000'
      dataSamplesStoredLimit: 100000
      displaySidebar: true
      dnsThreshold: 0.5
      domInteractiveThreshold: 5
      errorSamplesStoredLimit: 1000
      excludePatterns:
        -
          pattern: '/webperf/.*'
        -
          pattern: '/cpresources/.*'
        -
          pattern: /rss
      filterBotUserAgents: true
      firstByteThreshold: 2
      firstContentfulPaintThreshold: 5
      firstPaintThreshold: 5
      includeBeacon: true
      includeCraftProfiling: true
      includeCraftWarnings: false
      pageLoadThreshold: 10
      pluginName: Webperf
      rateLimitMs: 500
      staticCachedSite: false
      trimOutlierDataSamples: true
      webpageTestApiKey: ''
system:
  edition: pro
  live: true
  name: devMode.fm
  retryDuration: 60
  schemaVersion: 3.7.7
  timeZone: America/New_York
